### PR TITLE
Add README to HTTP_CONFORMANCE

### PR DESCRIPTION
**Pull request by attia-mahmoud**

### CODE REVIEW

**Comment by BenIlies** [comment]
Your readme contains issues:
- You inverted the headers of the HTTP/1 and HTTP/2
- You present HTTP/2 but the files you give are not for HTTP/2 (only for HTTP/1)

**Comment by attia-mahmoud** [comment]
fixed.

**Comment by BenIlies** [comment]
Actually we need one folder for HTTP 1 conformance and one for HTTP 2 conformance from the root level,
+TCP_SYNC
--- files
--- readme.md
+ HTTP_1
--- files
--- readme.md
+ HTTP_2
--- files
--- readme.md

something like this

**Comment by attia-mahmoud** [comment]
done.

**Pull request merged**
